// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      return App.__super__.constructor.apply(this, arguments);
    }

    App.prototype.initialize = function() {
      var deck;
      this.set('deck', deck = new Deck());
      this.set('playerHand', deck.dealPlayer());
      return this.set('dealerHand', deck.dealDealer());
    };

    App.prototype.winner = function() {
      var houseFinalScore, playerFinalScore;
      playerFinalScore = (this.get('playerHand')).scores();
      (this.get('dealerHand')).models[0].flip();
      while ((this.get('dealerHand')).scores() < 17) {
        (this.get('dealerHand')).hit();
      }
      houseFinalScore = (this.get('dealerHand')).scores();
      if (houseFinalScore > 21) {
        return this.trigger('playerWon', this);
      } else if (playerFinalScore > houseFinalScore) {
        return this.trigger('playerWon', this);
      } else {
        return this.trigger('playerLost', this);
      }
    };

    return App;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=App.map
