// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      return Hand.__super__.constructor.apply(this, arguments);
    }

    Hand.prototype.model = Card;

    Hand.prototype.initialize = function(array, deck, isDealer) {
      this.deck = deck;
      this.isDealer = isDealer;
    };

    Hand.prototype.hit = function() {
      this.add(this.deck.pop()).last();
      if (this.scores()[0] > 21) {
        this.trigger('playerLost', this);
      }
      if (this.scores()[0] === 21) {
        return this.trigger('playerWon', this);
      }
    };

    Hand.prototype.stand = function(self) {
      return self.model.winner();
    };

    Hand.prototype.scores = function() {
      var Aces, hasAce, numAces, score;
      hasAce = this.reduce(function(memo, card) {
        return memo || card.get('value') === 1;
      }, false);
      Aces = this.filter(function(c) {
        if (c.get('revealed' && c.get('value' === 1))) {
          return c;
        }
      });
      numAces = Aces.length;
      console.log(Aces);
      score = this.reduce(function(score, card) {
        return score + (card.get('revealed') ? card.get('rank') : 0);
      }, 0);
      if (hasAce && score + 10 <= 21) {
        return [score + 10];
      } else {
        return [score];
      }
    };

    return Hand;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=Hand.map
